---
- name: Converge
  hosts: localhost
  gather_facts: false
  environment:
    K8S_AUTH_HOST: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_HOST') }}"
    K8S_AUTH_API_KEY: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_API_KEY') }}"
  tasks:
    - name: Include the Role "test_app"
      ansible.builtin.include_role:
        name: operations.applications.test_app
