---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scc-deletion
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-scc-deletion
  annotations:
    argocd.argoproj.io/sync-wave: "3"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: scc-deletion
  apiGroup: rbac.authorization.k8s.io