kind: CheCluster
apiVersion: org.eclipse.che/v2
metadata:
  name: devspaces
  namespace: ansible-dev
spec:
  components: {}
  containerRegistry: {}
  devEnvironments: {}
  gitServices: {}
  networking: {}