---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include the Role "test_app"
      ansible.builtin.include_role:
        name: operations.applications.test_app
      vars:
        app_name: "molecule"
        app_image: "openshift/hello-openshift:latest"
        app_port: "8080"
        content_output: "Hello OpenShift!"
        app_namespace: "{{ lookup('ansible.builtin.env', 'APP_NAMESPACE') }}"
