---
- name: Destroy
  hosts: localhost
  gather_facts: false
  vars:
    app_name: "molecule"
    app_image: "openshift/hello-openshift:latest"
    app_port: "8080"
    content_output: "Hello OpenShift!"
  tasks:

    - name: Include role vars
      ansible.builtin.include_vars:
        file: ../../roles/test_app/vars/main.yml

    - name: Destroy namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ app_namespace }}"
        state: absent
        validate_certs: false
