apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  generation: 1
  labels:
  # TODO: update labels
    app.kubernetes.io/instance: collection-ci
    app.kubernetes.io/name: collection-ci
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/runtime: ansible
    pipeline.openshift.io/type: kubernetes
  name: collection-ci-ci
  namespace: demo-tekton
  annotations:
    argocd.argoproj.io/sync-wave: "38"
spec:
  params:
    - default: collection-ci
      name: APP_NAME
      type: string
      # TODO: use gitea
    - default: 'https://github.com/clbartolome/automation-developer-hub'
      name: GIT_REPO
      type: string
    - default: ''
      name: GIT_REVISION
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
  workspaces: 
    - workspace
    # ------------ FETCH REPOSITORY ------------ #
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    # ------------ LINT ANALYSIS ------------ #
    - name: lint-test
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: mock
      params:
        - name: MOCK_MSG
          value: unit-test
    # ------------ MOLECULE TEST ------------ #
    - name: code-analysis
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: mock
      params:
        - name: MOCK_MSG
          value: code-analysis
