apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  generation: 1
  labels:
  # TODO: update labels
    app.kubernetes.io/instance: collection-ci
    app.kubernetes.io/name: collection-ci
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/runtime: ansible
    pipeline.openshift.io/type: kubernetes
  name: collection-ci-ci
  # namespace: demo-tekton
  annotations:
    argocd.argoproj.io/sync-wave: "38"
spec:
  params:
    - default: operations.applications
      name: COLLECTION_NAME
      type: string
      # TODO: use gitea
    - default: 'http://gitea.gitea.svc.cluster.local:3000/gitea/operations.applications'
      name: GIT_REPO
      type: string
    - default: ''
      name: GIT_REVISION
      type: string
    # ------------ FETCH REPOSITORY ------------ #
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: source-code/$(params.COLLECTION_NAME)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    # ------------ TEST ------------ #
    - name: ansible-lint-test
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: ansible-lint
      params:
        - name: COLLECTION_NAME
          value: $(params.COLLECTION_NAME)
        - name: CODE_DIR
          value: source-code
      workspaces:
        - name: working-dir
          workspace: workspace
  workspaces:
    - name: workspace
