apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
  # namespace: demo-tekton
  annotations:
    description: |
      tasks for testing porposes.
    argocd.argoproj.io/sync-wave: "38"
spec:
  params:
    - name: MOCK_MSG
      description: Mock message
  stepTemplate:
    env:
      - name: HOME
        value: /tekton/home
      - name: SOURCE_DIR
        value: /workspace/source
  steps:
    - name: mock-step
      image: quay.io/ansible/awx-ee
      script: |
        echo "***** Test task *****"
        echo $(params.MOCK_MSG)

        ansible --version

        ls $SOURCE_DIR
  workspaces:
    - mountPath: /workspace/source
      name: source

        