apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-release
  namespace: ansible-dev
spec:
  workspaces:
    - name: source
      description: The workspace where cicd repo will be modified.
  params:
    - name: GIT_REPO
      type: string
    - name: PATH_CONTEXT
      type: string
    - name: CONFIGURATION_SECRET
      type: string
    - name: PIPELINERUN_URL
      type: string
    - name: COLLECTION_VERSION
      type: string
    - name: COLLECTION_NAME
      type: string
    - name: COLLECTION_NAMESPACE
      type: string
  stepTemplate:
    envFrom:
      - secretRef:
          name: $(params.CONFIGURATION_SECRET)
  steps:
    - name: create-release
      image: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8:v1.14.4-1
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
      script: |

        export AUTH_REPO=$(echo $(params.GIT_REPO) | sed -E "s#https://(.*)#https://$GITHUB_TOKEN@\1#g")

        git config --global user.email "tekton@redhat.com"
        git config --global user.name "tekton"

        git tag "$(params.COLLECTION_VERSION)" $(git rev-parse HEAD) --message "$(params.PATH_CONTEXT)"
        git push $AUTH_REPO "$(params.COLLECTION_VERSION)"

        RELEASE_NOTES="# $(params.COLLECTION_NAMESPACE).$(params.COLLECTION_NAME) $(params.COLLECTION_VERSION)\n\n$(params.PATH_CONTEXT) new release generated by CICD process.\n\n### Collection:\n\n- **hub.com/1**\n\n### Tekton pipeline:\n\n[View Tekton pipeline in OpenShift]($(params.PIPELINERUN_URL))"

        cat <<EOF > $(workspaces.source.path)/pr.json
        {
          "tag_name": "$(params.COLLECTION_VERSION)",
          "name": "$(params.COLLECTION_VERSION)",
          "prerelease": false,
          "body": "${RELEASE_NOTES}"
        }
        EOF
        cat $(workspaces.source.path)/pr.json

        RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -d @$(workspaces.source.path)/pr.json \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/zaskan/$(params.PATH_CONTEXT)/releases)

