apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unit
  namespace: ansible-dev
spec:
  params:
    - name: PROJECT_ROOT
      type: string
    - name: UNIT_TEST_PATH
      type: string
    - name: UNIT_COMMAND
      type: string
      default: ansible-test  
  workspaces:
    - name: source
      description: The workspace where app code has been cloned
  steps:
    - name: run-unit
      image: ghcr.io/ansible/community-ansible-dev-tools:v25.2.1 # v25.2.1
      workingDir: $(workspaces.source.path)
      script: |

        echo "Running Unit Test..."
        cd $(params.PROJECT_ROOT)/$(params.UNIT_TEST_PATH)
        $(params.UNIT_COMMAND) units --coverage  
        echo "Running Coverage Test..."
        $(params.UNIT_COMMAND) coverage report 


