apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unit
  namespace: ansible-dev
spec:
  params:
    - name: PROJECT_ROOT
      type: string
    - name: UNIT_TEST_PATH
      type: string
    - name: COLLECTION_PATH
      type: string
    - name: UNIT_COMMAND
      type: string
      default: pytest
  workspaces:
    - name: source
      description: The workspace where app code has been cloned
  steps:
    - name: run-unit
      image: ghcr.io/ansible/community-ansible-dev-tools:v25.2.1 # v25.2.1
      workingDir: $(workspaces.source.path)
      script: |
        git config --global --add safe.directory $(workspaces.source.path)/$(params.PROJECT_ROOT)
        echo "Running Unit Test..."
        cd $(params.PROJECT_ROOT)/$(params.UNIT_TEST_PATH)
        $(params.UNIT_COMMAND) -v
        echo "Running Coverage Test..."
        $(params.UNIT_COMMAND) $(params.COLLECTION_PATH).plugins.modules --cov-report=term-missing


