apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: integration
  namespace: ansible-dev
spec:
  params:
    - name: PROJECT_ROOT
      type: string
    - name: COLLECTION_PATH
      type: string
    - name: INTEGRATION_TEST_PATH
      type: string
    - name: INTEGRATION_COMMAND
      type: string
      default: ansible-test integration --start-at api_manage
  workspaces:
    - name: source
      description: The workspace where app code has been cloned
  steps:
    - name: run-integration
      image: ghcr.io/ansible/community-ansible-dev-tools:v25.2.1 # v25.2.1
      workingDir: $(workspaces.source.path)
      script: |
        git config --global --add safe.directory $(workspaces.source.path)/$(params.PROJECT_ROOT)
        echo "Running Integration Tests..."
        cd $(params.PROJECT_ROOT)/$(params.INTEGRATION_TEST_PATH) 
        $(params.INTEGRATION_COMMAND) 


