apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sanity
  namespace: ansible-dev
spec:
  params:
    - name: PROJECT_ROOT
      type: string
    - name: SANITY_COMMAND
      type: string
      default: ansible-test sanity --python 3.13.2 --local
  workspaces:
    - name: source
      description: The workspace where app code has been cloned
  steps:

    - name: set-git-safe-directory
      image: ghcr.io/ansible/community-ansible-dev-tools:v25.2.1
      workingDir: $(workspaces.source.path)
      script: |
        echo "Setting Git safe directory for: $(workspaces.source.path)/$(params.PROJECT_ROOT)"
        git config --global --add safe.directory $(workspaces.source.path)/$(params.PROJECT_ROOT)

    - name: run-sanity
      image: ghcr.io/ansible/community-ansible-dev-tools:v25.2.1 # v25.2.1
      workingDir: $(workspaces.source.path)/$(params.PROJECT_ROOT)
      script: |

        echo "Running Sanity Test..."
        $(params.SANITY_COMMAND) 

