collections:
  - name: community.general
  - name: https://github.com/zaskan/demos.utils.git
    type: git
    version: 1.0.8
  - name: https://github.com/zaskan/ansible_automation_platform.casc.git
    type: git
    version: main