apiVersion: batch/v1
kind: Job
metadata:
  generateName: gitea-setup-
  name: configure-gitea
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "19"
  labels:
      app.kubernetes.io/part-of: gitea
      name: configure-gitea
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: git
        image: quay.io/calopezb/git-utils:1.0.0
        # TODO: Read CONFIGURATION using a configmap
        env:
        - name: GITEA_HOSTNAME
          value: "gitea.gitea.svc.cluster.local:3000"
        command:
        - /bin/sh
        - '-c'
        args:
        # TODO: change clone repo branch to master
        #Example: https://github.com/clbartolome/ocp-dev-101/blob/master/environment/resources/10_gitea/setup-job.yaml
        - |-
          pwd
          mkdir repository
          cd repository
          echo "-- Creating gitea user"
          curl -X POST \
            -d '{"username":"gitea","password":"openshift","retype":"openshift","email":"gitea@gitea.com","send_notify":false}' \
            -H "Content-Type: application/json" \
            http://$GITEA_HOSTNAME/user/sign_up
          
          echo "-- Creating demo repository --"
          git clone -b argo_instalation https://github.com/clbartolome/automation-developer-hub   
          echo "------------------------------"   

          echo "-- Creating applications collection repository --"
          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST \
            -u gitea:openshift \
            -d '{"auto_init": true,"default_branch": "master","gitignores": "VisualStudioCode","name": "operations.applications","private": false,"trust_model": "default"}' \
            -H "Content-Type: application/json" \
            http://$GITEA_HOSTNAME/api/v1/user/repos)

          if [ "$RESPONSE" != "201" ]; then
              echo "Error creating repository, error code: $RESPONSE"
              exit 1
          fi

          git clone http://gitea:openshift@$GITEA_HOSTNAME/gitea/operations.applications
          cp -r automation-developer-hub/ansible-collections/operations.applications/. operations.applications
          cd operations.applications
          git config user.email "gitea@gitea.com"
          git config user.name "gitea"
          git add . && git commit -m "Repository cloned from demo source" && git push
          cd ..
          echo "------------------------------"   

          
        imagePullPolicy: Always
      restartPolicy: Never